# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Zachary Marasia
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Zachary Marasia
description              : Zachary Marasia - Projects and CV 
baseurl                  : "/Users/zachary.marasia/Desktop/fa25-portfolio-znm5-netizen/_projects/10/3/25 ENGRD 2020 HW 5.md" # Set this to your repo name 

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light/aqua # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /_projects/10/3/25 ENGRD 2020 HW 5.md/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

